# Generated by Django 4.0.6 on 2023-07-29 07:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsmodels_new_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodels',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=True, populate_from='news_title', unique=True),
        ),
    ]
