# Generated by Django 4.0.6 on 2023-07-29 08:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsmodels_new_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodels',
            name='new_slug',
        ),
        migrations.AddField(
            model_name='newsmodels',
            name='news_slug',
            field=autoslug.fields.AutoSlugField(blank=True, default=None, editable=True, null=True, populate_from='news_title'),
        ),
    ]
