# Generated by Django 4.0.6 on 2023-07-29 08:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_newsmodels_new_slug_newsmodels_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodels',
            name='news_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=True, populate_from='news_title'),
        ),
    ]
