# Generated by Django 4.0.6 on 2023-07-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_userdemoforms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userForms',
            new_name='userFormsDemo',
        ),
    ]
